import java.awt.GraphicsEnvironment;

/*
 * The code in this file was generated by ChatGPT.
 * This code is used to display the names of all the possible fonts that can be used.
 */
public class AvailableFonts {
    public static void main(String[] args) {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String[] fontNames = ge.getAvailableFontFamilyNames();
        for (String fontName : fontNames) {
            System.out.println(fontName);
        }
    }
}
